### PR TITLE
Add support of the curve methods for UE 5.3

### PR DESCRIPTION
**Pull request by Meruman**
Support of the "DumpSkeletonCurveNames", "CheckForMissingCurveNames" and "AddSkeletonCurve" methods for unreal engine version 5.3.0. Reason: the "AddSmartNameAndModify", "FSmartNameMapping" and a lot of other methods from the Skeleton class are now deprecated and no longer used.

### CODE REVIEW

**Comment by AchimTuran** [comment]
Thank you so much for creating this pull request! Do you already know if this will break support for 5.0, 5.1 and 5.2?

**Comment by Meruman** [comment]
Hi, sorry for the confusion, FSmartNameMapping class is still in the engine but some methods have changed. Everything is in this commit:
[https://github.com/EpicGames/UnrealEngine/commit/502797ca50c381928f5dec3edac62208811a8417](https://github.com/EpicGames/UnrealEngine/commit/502797ca50c381928f5dec3edac62208811a8417)

And this are some of the methods that will be deprecated from the Skeleton.h file.
image

I haven't tried it in 5.0,5.1 and 5.2 yet, it should not break support for those versions because I checked first if the engine is 5.3 or bigger but I will test it later today :)

**Comment by Meruman** [comment]
I just tested this code in 5.0, 5.1 and 5.2 without problems :)

**Comment by AchimTuran** [comment]
Sorry I missed your last message. I will take a deeper look into your changes next week. 😉

**Comment by spcarso** [comment]
I am on 5.3 and am stuck at this point.  Your course is the first time I have touched C++ so I don't really know how to proceed.  Anyway you could post here what I should change from your video?

**Comment by AchimTuran** [comment]
@Meruman 
Sorry for the long time I was not active. I needed a break. But the changes you did do not work with 5.3. The first error that occured is the new path for `IKRigSolver.h`. I really wonder how you got TTToolbox working with this branch.
grafik

**Comment by AchimTuran** [comment]
@spcarso 
```
I am on 5.3 and am stuck at this point. Your course is the first time I have touched C++ so I don't really know how to proceed. Anyway you could post here what I should change from your video?
```
You should use the version I was using to following the videos if it is your first time touching C++. Many guys already tried to get the code base working with 5.3 but none so far made everything work. 😅

**Comment by AchimTuran** [comment]
Not sure yet if I will take over the changes in #48. As this pull request will not result in a successful build!

**Comment by AchimTuran** [comment]
Minimal needed changes for 5.3 are now available in #48.
As so much has changed in 5.3 it is not possible to support 5.1 or 5.0 anymore.

Also a lot more effort needs to be spend to get TTToolbox fully working in5.3. it's the reason why I now Close this PR. 😉
5.3 support will be available soon.

**Pull request closed without merging**
